package com.stone.dao;

import java.util.List;

import com.stone.entity.Departments;

public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.DEPARTMENTS
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.DEPARTMENTS
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int insert(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.DEPARTMENTS
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int insertSelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.DEPARTMENTS
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    Departments selectByPrimaryKey(Integer departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.DEPARTMENTS
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.DEPARTMENTS
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int updateByPrimaryKey(Departments record);
    
    /**
     * 
     * @param department_id
     * @return
     */
    List<Departments> selectDepartmentsById(int department_id);
}