package com.stone.dao;

import java.util.List;
import java.util.Set;

import com.stone.entity.Employees;

public interface EmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMPLOYEES
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMPLOYEES
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int insert(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMPLOYEES
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int insertSelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMPLOYEES
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    Employees selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMPLOYEES
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int updateByPrimaryKeySelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMPLOYEES
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    int updateByPrimaryKey(Employees record);
    
    
    Employees selectEmployeesById(Integer id);
    
    List<Employees> selectManagerById(Integer id);
}