package com.stone.entity;

import java.util.List;

public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.DEPARTMENTS.LOCATION_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Integer locationId;
    
    private List<Employees> employees;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.DEPARTMENTS.DEPARTMENT_ID
     *
     * @return the value of HR.DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.DEPARTMENTS.DEPARTMENT_ID
     *
     * @param departmentId the value for HR.DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.DEPARTMENTS.DEPARTMENT_NAME
     *
     * @return the value of HR.DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.DEPARTMENTS.DEPARTMENT_NAME
     *
     * @param departmentName the value for HR.DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.DEPARTMENTS.MANAGER_ID
     *
     * @return the value of HR.DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.DEPARTMENTS.MANAGER_ID
     *
     * @param managerId the value for HR.DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.DEPARTMENTS.LOCATION_ID
     *
     * @return the value of HR.DEPARTMENTS.LOCATION_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.DEPARTMENTS.LOCATION_ID
     *
     * @param locationId the value for HR.DEPARTMENTS.LOCATION_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

	public List<Employees> getEmployees() {
		return employees;
	}

	public void setEmployees(List<Employees> employees) {
		this.employees = employees;
	}

	@Override
	public String toString() {
		return "Departments [departmentId=" + departmentId + ", departmentName=" + departmentName + ", managerId="
				+ managerId + ", locationId=" + locationId + ", employees=" + employees + "]";
	}

}