package com.stone.entity;

import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.EMPNO
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private Integer empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.ENAME
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.JOB
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.MGR
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private Integer mgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.HIREDATE
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private Date hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.SAL
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private Double sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.COMM
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private Double comm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.DEPTNO
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    private Integer deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.EMPNO
     *
     * @return the value of HR.EMP.EMPNO
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.EMPNO
     *
     * @param empno the value for HR.EMP.EMPNO
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.ENAME
     *
     * @return the value of HR.EMP.ENAME
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.ENAME
     *
     * @param ename the value for HR.EMP.ENAME
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.JOB
     *
     * @return the value of HR.EMP.JOB
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.JOB
     *
     * @param job the value for HR.EMP.JOB
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.MGR
     *
     * @return the value of HR.EMP.MGR
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public Integer getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.MGR
     *
     * @param mgr the value for HR.EMP.MGR
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setMgr(Integer mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.HIREDATE
     *
     * @return the value of HR.EMP.HIREDATE
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.HIREDATE
     *
     * @param hiredate the value for HR.EMP.HIREDATE
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.SAL
     *
     * @return the value of HR.EMP.SAL
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public Double getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.SAL
     *
     * @param sal the value for HR.EMP.SAL
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setSal(Double sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.COMM
     *
     * @return the value of HR.EMP.COMM
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public Double getComm() {
        return comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.COMM
     *
     * @param comm the value for HR.EMP.COMM
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setComm(Double comm) {
        this.comm = comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.DEPTNO
     *
     * @return the value of HR.EMP.DEPTNO
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.DEPTNO
     *
     * @param deptno the value for HR.EMP.DEPTNO
     *
     * @mbg.generated Tue Nov 20 11:31:24 CST 2018
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

	@Override
	public String toString() {
		return "Emp [empno=" + empno + ", ename=" + ename + ", job=" + job + ", mgr=" + mgr + ", hiredate=" + hiredate
				+ ", sal=" + sal + ", comm=" + comm + ", deptno=" + deptno + "]";
	}
}