package com.stone.entity;

import java.util.Date;
import java.util.List;
import java.util.Set;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.EMAIL
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.JOB_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.SALARY
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Double salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.COMMISSION_PCT
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Double commissionPct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    private Integer departmentId;
    
    private Departments departments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.EMPLOYEE_ID
     *
     * @return the value of HR.EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.EMPLOYEE_ID
     *
     * @param employeeId the value for HR.EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.FIRST_NAME
     *
     * @return the value of HR.EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.FIRST_NAME
     *
     * @param firstName the value for HR.EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.LAST_NAME
     *
     * @return the value of HR.EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.LAST_NAME
     *
     * @param lastName the value for HR.EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.EMAIL
     *
     * @return the value of HR.EMPLOYEES.EMAIL
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.EMAIL
     *
     * @param email the value for HR.EMPLOYEES.EMAIL
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.PHONE_NUMBER
     *
     * @return the value of HR.EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.PHONE_NUMBER
     *
     * @param phoneNumber the value for HR.EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.HIRE_DATE
     *
     * @return the value of HR.EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.HIRE_DATE
     *
     * @param hireDate the value for HR.EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.JOB_ID
     *
     * @return the value of HR.EMPLOYEES.JOB_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.JOB_ID
     *
     * @param jobId the value for HR.EMPLOYEES.JOB_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.SALARY
     *
     * @return the value of HR.EMPLOYEES.SALARY
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.SALARY
     *
     * @param salary the value for HR.EMPLOYEES.SALARY
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.COMMISSION_PCT
     *
     * @return the value of HR.EMPLOYEES.COMMISSION_PCT
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Double getCommissionPct() {
        return commissionPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.COMMISSION_PCT
     *
     * @param commissionPct the value for HR.EMPLOYEES.COMMISSION_PCT
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setCommissionPct(Double commissionPct) {
        this.commissionPct = commissionPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.MANAGER_ID
     *
     * @return the value of HR.EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.MANAGER_ID
     *
     * @param managerId the value for HR.EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMPLOYEES.DEPARTMENT_ID
     *
     * @return the value of HR.EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMPLOYEES.DEPARTMENT_ID
     *
     * @param departmentId the value for HR.EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Fri Nov 23 11:23:10 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

	@Override
	public String toString() {
		return "Employees [employeeId=" + employeeId + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", email=" + email + ", phoneNumber=" + phoneNumber + ", hireDate=" + hireDate + ", jobId=" + jobId
				+ ", salary=" + salary + ", commissionPct=" + commissionPct + ", managerId=" + managerId
				+ ", departmentId=" + departmentId + "]";
	}

	public Departments getDepartments() {
		return departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}
  
}