package com.stone.orm;

import java.math.BigDecimal;
import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.EMPNO
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private int empno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.ENAME
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.JOB
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.MGR
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private int mgr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.HIREDATE
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private Date hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.SAL
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private double sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.COMM
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private double comm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HR.EMP.DEPTNO
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    private int deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.EMPNO
     *
     * @return the value of HR.EMP.EMPNO
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public int getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.EMPNO
     *
     * @param i the value for HR.EMP.EMPNO
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setEmpno(int i) {
        this.empno = i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.ENAME
     *
     * @return the value of HR.EMP.ENAME
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.ENAME
     *
     * @param ename the value for HR.EMP.ENAME
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.JOB
     *
     * @return the value of HR.EMP.JOB
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.JOB
     *
     * @param job the value for HR.EMP.JOB
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.MGR
     *
     * @return the value of HR.EMP.MGR
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public int getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.MGR
     *
     * @param i the value for HR.EMP.MGR
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setMgr(int i) {
        this.mgr = i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.HIREDATE
     *
     * @return the value of HR.EMP.HIREDATE
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.HIREDATE
     *
     * @param hiredate the value for HR.EMP.HIREDATE
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.SAL
     *
     * @return the value of HR.EMP.SAL
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public double getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.SAL
     *
     * @param d the value for HR.EMP.SAL
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setSal(double d) {
        this.sal = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.COMM
     *
     * @return the value of HR.EMP.COMM
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public double getComm() {
        return comm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.COMM
     *
     * @param d the value for HR.EMP.COMM
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setComm(double d) {
        this.comm = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HR.EMP.DEPTNO
     *
     * @return the value of HR.EMP.DEPTNO
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public int getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HR.EMP.DEPTNO
     *
     * @param i the value for HR.EMP.DEPTNO
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    public void setDeptno(int i) {
        this.deptno = i;
    }
}