package com.stone.orm;

import com.stone.orm.Emp;
import com.stone.orm.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    long countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HR.EMP
     *
     * @mbg.generated Wed Nov 14 15:21:59 CST 2018
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);
}